# Generated by Django 6.0 on 2025-12-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_tipo', models.CharField(max_length=50)),
                ('c_banco', models.CharField(max_length=50)),
                ('c_nombre', models.CharField(max_length=100)),
                ('u_rut', models.CharField(max_length=12)),
                ('c_estado', models.BooleanField(default=True)),
                ('c_cupo', models.IntegerField(blank=True, null=True)),
                ('c_usado', models.IntegerField(blank=True, null=True)),
                ('c_disponible', models.IntegerField(blank=True, null=True)),
                ('c_lineaCredito', models.BooleanField(blank=True, default=False, null=True)),
                ('c_lineaCupo', models.IntegerField(blank=True, null=True)),
                ('c_lineaUsado', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
