# Generated by Django 6.0 on 2025-12-31 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_nombres', models.CharField(max_length=100)),
                ('u_apellidos', models.CharField(max_length=100)),
                ('u_correo', models.EmailField(max_length=100, unique=True)),
                ('u_password', models.CharField(max_length=100)),
                ('u_rut', models.CharField(max_length=12, unique=True)),
                ('u_edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('p_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
