# Generated by Django 6.0 on 2026-01-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_tipo', models.CharField(max_length=50)),
                ('m_monto', models.IntegerField()),
                ('m_motivo', models.TextField()),
                ('m_fecha', models.DateField()),
                ('m_persona', models.CharField(default='0')),
                ('c_id', models.IntegerField()),
                ('u_rut', models.CharField(max_length=12)),
            ],
        ),
    ]
